// Generates the portal pages from the registry in lib/portals.js:
//   portal/index.html                       the public hub
//   portal/<id>/login.html                  sign in            (public)
//   portal/<id>/request-access.html         request access     (public)
//   portal/<id>/forgot.html                 forgot password    (public)
//   portal/<id>/reset.html                  set / reset password (public, token in link)
//   portal/<id>/home.html                   dashboard          (protected by middleware.js)
//   portal/<id>/account.html                account            (protected by middleware.js)
//
// Each page carries empty AHO sentinel blocks; the shared header, footer
// and chrome are stamped by the usual run afterwards:
//   node scripts/build-portals.js && node scripts/propagate-nav.js && node scripts/propagate-chrome.js && node scripts/check-nav.js
// Links inside the pages are absolute (/portal/...) because Vercel serves
// them at their real paths; the stamped chrome uses relative paths.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const FONTS_HREF = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;1,400;1,500&family=Inter:wght@400;500;600&display=swap';
const ver = rel => crypto.createHash('sha1').update(fs.readFileSync(path.join(ROOT, rel))).digest('hex').slice(0, 8);
const LEGAL = 'Aho Farms products are prescription medicines and are not for general sale. Portal access is restricted to verified professionals and partners; every request is reviewed by Aho Farms before an account is approved.';

const S = {
  nav: ['<!-- AHO:NAV:START - generated by scripts/propagate-nav.js, do not edit by hand -->', '<!-- AHO:NAV:END -->'],
  css: ['<!-- AHO:CHROME:CSS:START - generated by scripts/propagate-chrome.js, do not edit by hand -->', '<!-- AHO:CHROME:CSS:END -->'],
  js: ['<!-- AHO:CHROME:JS:START - generated by scripts/propagate-chrome.js, do not edit by hand -->', '<!-- AHO:CHROME:JS:END -->'],
  footer: ['<!-- AHO:FOOTER:START - generated by scripts/propagate-nav.js, do not edit by hand -->', '<!-- AHO:FOOTER:END -->'],
};

function shell({ depth, title, description, portalId, page, main, noindex, scripts = [] }) {
  const rel = '../'.repeat(depth);
  const fav = (fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8').match(/<link rel="icon"[^>]*>/) || [''])[0]
    .replace(/href="(?!https?:|\/|data:)/, `href="${rel}`);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">${noindex ? '\n  <meta name="robots" content="noindex, nofollow">' : ''}${fav ? '\n  ' + fav : ''}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="${FONTS_HREF}" rel="stylesheet">
  ${S.css[0]}
  ${S.css[1]}
  <link rel="stylesheet" href="${rel}assets/aho-portal.css?v=${ver('assets/aho-portal.css')}">
</head>
<body data-portal="${esc(portalId)}" data-page="${esc(page)}">
${S.nav[0]}
${S.nav[1]}
<main id="main" class="pt-main">
${main}
</main>
${S.footer[0]}
${S.footer[1]}
${S.js[0]}
${S.js[1]}
${scripts.map(x => `<script src="${rel}${x}?v=${ver(x)}" defer></script>\n`).join('')}<script src="${rel}assets/aho-portal.js?v=${ver('assets/aho-portal.js')}" defer></script>
</body>
</html>
`;
}

const msg = (role = 'alert', live = 'assertive') => `<p class="pt-msg" role="${role}" aria-live="${live}" tabindex="-1" hidden></p>`;
const fieldError = '<span class="pt-field-error" aria-live="polite"></span>';

function field(f, { full = false, id } = {}) {
  const fid = id || `f-${f.name}`;
  const req = f.required ? ' data-required required aria-required="true"' : '';
  const ac = f.autocomplete ? ` autocomplete="${f.autocomplete}"` : '';
  const star = f.required ? ' <span aria-hidden="true">*</span>' : '';
  let control;
  if (f.type === 'select') {
    control = `<select id="${fid}" name="${f.name}"${req}>\n        <option value="">Select…</option>\n${f.options.map(o => `        <option value="${esc(o)}">${esc(o)}</option>`).join('\n')}\n      </select>`;
  } else if (f.type === 'textarea') {
    control = `<textarea id="${fid}" name="${f.name}" rows="${f.rows || 4}"${req}${ac}></textarea>`;
  } else {
    const im = f.type === 'tel' ? ' inputmode="tel"' : f.type === 'email' ? ' inputmode="email"' : '';
    control = `<input id="${fid}" name="${f.name}" type="${f.type}"${im}${ac}${req}>`;
  }
  return `      <div class="field${full || f.type === 'textarea' ? ' field--full' : ''}">
        <label for="${fid}">${esc(f.label)}${star}</label>
        ${control}${f.hint ? `\n        <small>${esc(f.hint)}</small>` : ''}
        ${fieldError}
      </div>`;
}

const pwField = (name, label, ac, hint) => `      <div class="field">
        <label for="f-${name}">${label}</label>
        <div class="pt-pw"><input id="f-${name}" name="${name}" type="password" autocomplete="${ac}" data-required required aria-required="true"${name !== 'current' ? ' minlength="10"' : ''}><button type="button" class="pt-pw-toggle" aria-pressed="false">Show</button></div>${hint ? `\n        <small>${hint}</small>` : ''}
        ${fieldError}
      </div>`;

function switchLine(p, all, text) {
  const others = all.filter(o => o.id !== p.id).map(o => `<a href="/portal/${o.id}/login.html">${esc(o.name)}</a>`).join('<span>·</span>');
  return `<p class="pt-switch">${text} ${others}</p>`;
}

/* ---------- pages ---------- */
function loginPage(p, all) {
  const main = `<section class="pt-plate pt-auth" aria-labelledby="ptTitle">
  <div class="pt-auth-grid">
    <div class="pt-story">
      <span class="eyebrow eyebrow--rule">Aho Farms · Portals</span>
      <h1 id="ptTitle">${esc(p.name)}</h1>
      <p class="pt-lead">${esc(p.tagline)}</p>
      <div class="pt-thread" aria-hidden="true"></div>
      <p class="pt-note">${esc(p.intro)}</p>
      ${switchLine(p, all, 'Looking for a different portal?')}
    </div>
    <form id="ptLogin" class="pt-form" novalidate>
      <div class="pt-form-head">
        <h2 class="pt-form-title">Sign in</h2>
        <p class="pt-form-sub">Approved ${esc(p.audience)} accounts only. ${esc(p.eligibility)}</p>
      </div>
      ${msg()}
      <div class="field">
        <label for="f-email">Email</label>
        <input id="f-email" name="email" type="email" inputmode="email" autocomplete="username" data-required required aria-required="true">
        ${fieldError}
      </div>
${pwField('password', 'Password', 'current-password')}
      <div class="pt-row">
        <label class="pt-check"><input type="checkbox" name="remember"> Keep me signed in</label>
        <a class="pt-link" href="/portal/${p.id}/forgot.html">Forgot password?</a>
      </div>
      <button class="btn btn--primary" type="submit"><span class="pt-btn-label">Sign in</span></button>
      <p class="pt-alt">Don't have an approved account? <a href="/portal/${p.id}/request-access.html">Request access</a></p>
    </form>
  </div>
</section>
<p class="pt-legal">${LEGAL}</p>`;
  return shell({ depth: 2, title: `${p.name} · Sign in | Aho Farms`, description: `Sign in to the Aho Farms ${p.name}. ${p.tagline}`, portalId: p.id, page: 'login', main });
}

function requestPage(p, all) {
  const fields = p.requestFields.map(f => field(f)).join('\n');
  const main = `<section class="pt-plate pt-auth pt-auth--request" aria-labelledby="ptTitle">
  <div class="pt-auth-grid">
    <div class="pt-story">
      <span class="eyebrow eyebrow--rule">${esc(p.name)}</span>
      <h1 id="ptTitle">Request access.</h1>
      <p class="pt-lead">${esc(p.eligibility)}</p>
      <div class="pt-thread" aria-hidden="true"></div>
      <ol class="pt-steps">
        <li><span><b>Tell us who you are</b>Your details and your organisation, so we can verify you.</span></li>
        <li><span><b>Aho Farms reviews the request</b>We check registration and licensing before any account is approved. Submitting a request does not grant access.</span></li>
        <li><span><b>Set your password and sign in</b>Once approved, you receive an email with a link to choose your password.</span></li>
      </ol>
      <p class="pt-switch">Already approved? <a href="/portal/${p.id}/login.html">Sign in</a></p>
    </div>
    <form id="ptRequest" class="pt-form" novalidate>
      <div class="pt-form-head">
        <h2 class="pt-form-title">${esc(p.name)} access request</h2>
        <p class="pt-form-sub">Fields marked * are required. We only use these details to verify and set up your access.</p>
      </div>
      ${msg()}
      <div class="pt-fields">
${fields}
      </div>
      <div class="pt-hp" aria-hidden="true"><label for="f-website">Website</label><input id="f-website" name="website" type="text" tabindex="-1" autocomplete="off"></div>
      <button class="btn btn--primary" type="submit"><span class="pt-btn-label">Send request</span></button>
      <p class="pt-alt">Questions first? Email <a href="mailto:${esc(p.support.email)}">${esc(p.support.email)}</a></p>
    </form>
  </div>
</section>
<p class="pt-legal">${LEGAL}</p>`;
  return shell({ depth: 2, title: `${p.name} · Request access | Aho Farms`, description: `Request access to the Aho Farms ${p.name}. ${p.eligibility}`, portalId: p.id, page: 'request-access', main });
}

function forgotPage(p) {
  const main = `<section class="pt-plate pt-auth pt-auth--narrow" aria-labelledby="ptTitle">
  <div class="pt-auth-grid">
    <form id="ptForgot" class="pt-form" novalidate>
      <div class="pt-form-head">
        <span class="eyebrow eyebrow--rule">${esc(p.name)}</span>
        <h1 id="ptTitle" class="pt-form-title">Reset your password</h1>
        <p class="pt-form-sub">Enter the email on your ${esc(p.name)} account and we will send a link to choose a new password.</p>
      </div>
      ${msg('status', 'polite')}
      <div class="field">
        <label for="f-email">Email</label>
        <input id="f-email" name="email" type="email" inputmode="email" autocomplete="username" data-required required aria-required="true">
        ${fieldError}
      </div>
      <button class="btn btn--primary" type="submit"><span class="pt-btn-label">Send reset link</span></button>
      <p class="pt-alt"><a href="/portal/${p.id}/login.html">Back to sign in</a></p>
    </form>
  </div>
</section>
<p class="pt-legal">${LEGAL}</p>`;
  return shell({ depth: 2, title: `${p.name} · Reset password | Aho Farms`, description: `Reset your Aho Farms ${p.name} password.`, portalId: p.id, page: 'forgot', main });
}

function resetPage(p) {
  const main = `<section class="pt-plate pt-auth pt-auth--narrow" aria-labelledby="ptTitle">
  <div class="pt-auth-grid">
    <form id="ptReset" class="pt-form" novalidate>
      <div class="pt-form-head">
        <span class="eyebrow eyebrow--rule">${esc(p.name)}</span>
        <h1 id="ptTitle" class="pt-form-title">Choose a new password</h1>
        <p class="pt-form-sub">At least 10 characters, with a letter and a number.</p>
      </div>
      ${msg('status', 'polite')}
${pwField('password', 'New password', 'new-password')}
${pwField('confirm', 'Confirm new password', 'new-password')}
      <button class="btn btn--primary" type="submit"><span class="pt-btn-label">Save password</span></button>
      <p class="pt-alt">Link expired? <a href="/portal/${p.id}/forgot.html">Request a new one</a></p>
    </form>
  </div>
</section>`;
  return shell({ depth: 2, title: `${p.name} · Set password | Aho Farms`, description: `Choose a password for your Aho Farms ${p.name} account.`, portalId: p.id, page: 'reset', main, noindex: true });
}

function homePage(p) {
  const skel = `<section class="pt-plate pt-sec plate--flax" aria-hidden="true">
    <div class="pt-sec-inner">
      <div class="pt-sec-copy"><div class="pt-skel pt-skel--line" style="width:30%"></div><div class="pt-skel pt-skel--line" style="width:70%;height:28px"></div><div class="pt-skel pt-skel--line" style="width:85%"></div></div>
      <div class="pt-cards"><div class="pt-skel pt-skel--card"></div><div class="pt-skel pt-skel--card"></div><div class="pt-skel pt-skel--card"></div><div class="pt-skel pt-skel--card"></div></div>
    </div>
  </section>`;
  const main = `<header class="pt-plate pt-dash-head">
  <div class="pt-inner">
    <div class="pt-dash-top">
      <div>
        <span class="eyebrow eyebrow--rule">${esc(p.name)}</span>
        <h1>Kia ora, <em data-user-name>&nbsp;</em></h1>
        <p class="pt-dash-headline" data-dash-headline hidden></p>
        <p class="pt-dash-lead" data-dash-lead>Loading your portal…</p>
      </div>
      <div class="pt-dash-meta">
        <dl>
          <dt>Signed in as</dt><dd data-user-email>&nbsp;</dd>
          <dt>Organisation</dt><dd data-user-org>&nbsp;</dd>
        </dl>
        <div class="btn-row">
          <a class="btn btn--ghost" href="/portal/${p.id}/account.html">Account</a>
          <a class="btn btn--ghost" href="/portal/" data-signout>Sign out</a>
        </div>
      </div>
    </div>
    <nav class="pt-jump" id="ptJump" aria-label="Portal sections"></nav>
  </div>
</header>
<div id="ptSections" aria-live="polite" aria-busy="true">
  ${skel}
</div>
<section class="pt-plate pt-support" id="support" aria-labelledby="ptSupportTitle">
  <div class="pt-support-inner">
    <div>
      <span class="eyebrow eyebrow--rule">${esc(p.support.label)}</span>
      <h2 id="ptSupportTitle">Need something you can't find here?</h2>
      <p>Email the Aho Farms team directly and we will come back to you. Tell us the product, batch or document you need and we will point you to it or add it to the portal.</p>
    </div>
    <div class="btn-row">
      <a class="btn btn--primary" data-support-mail href="mailto:${esc(p.support.email)}">${esc(p.support.email)}</a>
      <a class="btn btn--ghost" href="/contact.html">Contact page</a>
    </div>
  </div>
</section>
<noscript><p class="pt-legal">This portal needs JavaScript to load your resources.</p></noscript>`;
  return shell({ depth: 2, title: `${p.name} | Aho Farms`, description: `Aho Farms ${p.name}.`, portalId: p.id, page: 'home', main, noindex: true });
}

function accountPage(p) {
  const main = `<section class="pt-plate pt-account" id="ptAccount" aria-labelledby="ptTitle">
  <div class="pt-account-grid">
    <div>
      <span class="eyebrow eyebrow--rule">${esc(p.name)} · Account</span>
      <h1 id="ptTitle">Your account.</h1>
      <p class="pt-lead">The details Aho Farms holds for your portal access. To change your name, organisation or level of access, contact <a class="pt-link" href="mailto:${esc(p.support.email)}">${esc(p.support.email)}</a>.</p>
      <dl>
        <dt>Name</dt><dd data-user-name>&nbsp;</dd>
        <dt>Email</dt><dd data-user-email>&nbsp;</dd>
        <dt>Organisation</dt><dd data-user-org>&nbsp;</dd>
        <dt>Access</dt><dd data-user-role>&nbsp;</dd>
      </dl>
      <div class="btn-row" style="margin-top:var(--s4)">
        <a class="btn btn--ghost" href="/portal/${p.id}/home.html">Portal home</a>
        <a class="btn btn--ghost" href="/portal/" data-signout>Sign out</a>
      </div>
    </div>
    <form id="ptPassword" class="pt-form" novalidate>
      <div class="pt-form-head">
        <h2 class="pt-form-title">Change password</h2>
        <p class="pt-form-sub">At least 10 characters, with a letter and a number.</p>
      </div>
      ${msg('status', 'polite')}
${pwField('current', 'Current password', 'current-password')}
${pwField('password', 'New password', 'new-password')}
${pwField('confirm', 'Confirm new password', 'new-password')}
      <button class="btn btn--primary" type="submit"><span class="pt-btn-label">Update password</span></button>
    </form>
  </div>
</section>`;
  return shell({ depth: 2, title: `${p.name} · Account | Aho Farms`, description: `Your Aho Farms ${p.name} account.`, portalId: p.id, page: 'account', main, noindex: true });
}

function consumerPage(c, all, markets) {
  const faq = [
    ['What happens after I submit the form?', 'Aho Farms records your enquiry and matches it to the approved prescriber partner for your country. You then get your next step straight away: a link and QR code to that partner, or a message that the partner or the Aho Farms team will contact you.'],
    ['Will I definitely get a prescription?', 'No. The prescriber assesses your individual circumstances and decides whether medicinal cannabis is appropriate for you. Aho Farms has no part in that decision.'],
    ['Do I need a referral from my GP?', 'Usually not. You can consult an independent prescriber directly. Some clinics ask for a summary from your GP, so it is worth checking when you book.'],
    ['Is medicinal cannabis funded?', 'In New Zealand medicinal cannabis products are generally not funded, so you pay for the consultation and the medicine. Costs vary between clinics and pharmacies; ask before you book.'],
    ['Can Aho Farms prescribe or supply me directly?', 'No. Aho Farms is a licensed cultivator. Our products are prescription medicines, prescribed by independent healthcare providers and dispensed by pharmacies.'],
    ['How will my details be used?', 'To match you with a prescriber partner in your country, to make the introduction, and to follow up on your enquiry. We share them only with that partner, and only with your consent. See our privacy policy for the detail.'],
    ['Can I drive after using medicinal cannabis?', 'Driving while impaired is illegal and unsafe. Discuss driving, work and other activities with your prescriber before you start.'],
  ].map(([q, a]) => `        <details class="cs-faq-item"><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('\n');
  const countryOptions = markets.CONSUMER_MARKETS.map(x => `<option value="${esc(x)}">${esc(x)}</option>`).join('');
  const marketChips = markets.CONSUMER_MARKETS.map(x => `<li>${esc(x)}</li>`).join('\n        ');
  const main = `<section class="pt-plate cs-hero plate--flax" aria-labelledby="ptTitle">
  <div class="pt-inner cs-hero-grid">
    <div>
      <span class="eyebrow eyebrow--rule">Consumers · Patient access</span>
      <h1 id="ptTitle">Medicinal cannabis, through the right pathway.</h1>
      <p class="cs-lead">Looking to discuss whether medicinal cannabis may be appropriate for you? Tell us where you are and we will connect you with an approved, independent prescriber partner for your country.</p>
      <div class="btn-row">
        <a class="btn btn--primary" href="#get-connected">Get Connected to a Prescriber</a>
        <a class="btn btn--ghost" href="#how-it-works">How access works</a>
      </div>
    </div>
    <aside class="cs-hero-note" aria-label="How Aho Farms fits in">
      <span class="eyebrow">Where we fit</span>
      <p><b>Aho Farms grows the medicine. We don't prescribe it.</b> We introduce you to an independent prescriber who assesses your circumstances. Aho Farms does not prescribe, diagnose or guarantee a prescription.</p>
    </aside>
  </div>
</section>

<section class="pt-plate pt-sec pt-sec--ink cs-sec" id="how-it-works" aria-labelledby="csHowTitle">
  <div class="pt-inner">
    <div class="cs-sec-head">
      <span class="eyebrow eyebrow--rule">01 · How access works</span>
      <h2 id="csHowTitle">Four steps, all with independent healthcare providers.</h2>
    </div>
    <ol class="cs-steps">
      <li><b>Get connected</b><p>Tell us your country and how to reach you. Aho Farms introduces you to the approved prescriber partner for your market, by email, referral link or QR code.</p></li>
      <li><b>Consultation and assessment</b><p>The prescriber discusses your circumstances, what you have tried, and the possible benefits and risks. They decide whether medicinal cannabis is appropriate for you.</p></li>
      <li><b>Prescription</b><p>If it is, you receive a prescription for a specific product, dose and duration, and a plan for follow-up.</p></li>
      <li><b>Pharmacy</b><p>Take the prescription to a pharmacy that stocks the product. The pharmacist dispenses it and can answer questions about taking it.</p></li>
    </ol>
  </div>
</section>

<section class="pt-plate pt-sec plate--flax cs-sec" id="get-connected" aria-labelledby="csConnectTitle">
  <div class="pt-inner cs-connect-grid">
    <div class="cs-connect-copy">
      <span class="eyebrow eyebrow--rule">02 · Get Connected to a Prescriber</span>
      <h2 id="csConnectTitle">Tell us where you are. We'll make the introduction.</h2>
      <p>Submit your details once. Aho Farms matches you to the approved prescriber partner for your country and gives you your next step straight away.</p>
      <ol class="pt-steps pt-steps--light">
        <li><span><b>Choose your country and region</b>This decides which prescriber partner you are connected with.</span></li>
        <li><span><b>Tell us how to reach you</b>Name, email and mobile, and how you would like to be contacted. We only collect what is needed to route and support your enquiry, and nothing medical.</span></li>
        <li><span><b>Get your next step</b>A referral link and QR code to your partner, an email introduction, or a call-back, depending on your market.</span></li>
      </ol>
      <p class="cs-privacy">By submitting you agree to Aho Farms storing your details and sharing them with the approved prescriber partner for your country so they can contact you. We do not sell your information. <a href="/privacy.html">Privacy policy</a>.</p>
    </div>
    <form id="csConnect" class="pt-form pt-form--light" novalidate>
      <div class="pt-form-head">
        <h3 class="pt-form-title">Start your access enquiry</h3>
        <p class="pt-form-sub">Fields marked * are required. Takes about a minute.</p>
      </div>
      ${msg()}
      <div class="pt-fields">
        <div class="field"><label for="cs-first">First name <span aria-hidden="true">*</span></label><input id="cs-first" name="firstName" type="text" autocomplete="given-name" data-required required aria-required="true">${fieldError}</div>
        <div class="field"><label for="cs-last">Last name <span aria-hidden="true">*</span></label><input id="cs-last" name="lastName" type="text" autocomplete="family-name" data-required required aria-required="true">${fieldError}</div>
        <div class="field"><label for="cs-email">Email <span aria-hidden="true">*</span></label><input id="cs-email" name="email" type="email" inputmode="email" autocomplete="email" data-required required aria-required="true">${fieldError}</div>
        <div class="field"><label for="cs-phone">Mobile number <span aria-hidden="true">*</span></label><input id="cs-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" data-required required aria-required="true">${fieldError}</div>
        <div class="field"><label for="cs-country">Country <span aria-hidden="true">*</span></label><select id="cs-country" name="country" autocomplete="country-name" data-required required aria-required="true"><option value="">Select…</option>${countryOptions}</select>${fieldError}</div>
        <div class="field"><label for="cs-region">Region / state <span aria-hidden="true">*</span></label><input id="cs-region" name="region" type="text" list="csRegionList" autocomplete="address-level1" data-required required aria-required="true"><datalist id="csRegionList"></datalist>${fieldError}</div>
        <div class="field"><label for="cs-contact">Preferred contact</label><select id="cs-contact" name="contactMethod"><option value="">No preference</option><option>Email</option><option>Phone</option><option>Either</option></select>${fieldError}</div>
        <div class="field"><label for="cs-tele">Consultation preference</label><select id="cs-tele" name="telehealth"><option value="">No preference</option>${markets.TELEHEALTH_PREFS.filter(x => x !== 'No preference').map(x => `<option>${esc(x)}</option>`).join('')}</select>${fieldError}</div>
        <div class="field"><label for="cs-heard">How did you hear about Aho Farms?</label><select id="cs-heard" name="heardAbout"><option value="">Select…</option>${markets.HEARD_ABOUT.map(x => `<option>${esc(x)}</option>`).join('')}</select>${fieldError}</div>
        <div class="field"><label for="cs-message">General enquiry</label><textarea id="cs-message" name="message" rows="2"></textarea><small>Optional. Please don't include medical details; your prescriber will take those in your consultation.</small>${fieldError}</div>
        <div class="field field--full cs-consent">
          <label class="pt-check pt-check--top"><input type="checkbox" name="ageConfirmed" data-required required aria-required="true"><span>I confirm I am 18 years or older and meet the age requirement that applies in my country. <span aria-hidden="true">*</span></span></label>
          ${fieldError}
          <label class="pt-check pt-check--top"><input type="checkbox" name="consentReferral" data-required required aria-required="true"><span>I agree to Aho Farms storing my details and sharing them with the approved prescriber partner for my country so they can contact me about a consultation. <span aria-hidden="true">*</span></span></label>
          ${fieldError}
          <label class="pt-check pt-check--top"><input type="checkbox" name="consentMarketing"><span>Keep me informed about Aho Farms news and patient information by email.</span></label>
        </div>
      </div>
      <input type="hidden" name="source" value="consumer-portal"><input type="hidden" name="campaign" value=""><input type="hidden" name="referrer" value="">
      <div class="pt-hp" aria-hidden="true"><label for="cs-website">Website</label><input id="cs-website" name="website" type="text" tabindex="-1" autocomplete="off"></div>
      <button class="btn btn--primary" type="submit"><span class="pt-btn-label">Send my enquiry</span></button>
    </form>
  </div>
</section>

<section class="pt-plate pt-sec pt-sec--ink cs-sec" id="consultation" aria-labelledby="csExpectTitle">
  <div class="pt-inner">
    <div class="cs-sec-head">
      <span class="eyebrow eyebrow--rule">03 · What to expect</span>
      <h2 id="csExpectTitle">What a consultation usually involves.</h2>
    </div>
    <div class="cs-cols">
      <div class="cs-col"><h3>Before</h3><p>Have your health history to hand: current conditions, medicines and supplements, and what you have already tried. Write down the questions you want answered.</p></div>
      <div class="cs-col"><h3>During</h3><p>The prescriber talks through your circumstances, the evidence for your situation, possible side effects and interactions, and whether a trial is appropriate. Ask about costs, follow-up and what happens if it does not help.</p></div>
      <div class="cs-col"><h3>After</h3><p>If a product is prescribed you will usually start low and adjust with your prescriber's guidance, with a follow-up booked. Your pharmacist can help with practical questions about taking it.</p></div>
    </div>
  </div>
</section>

<section class="pt-plate pt-sec plate--cream cs-sec" id="faq" aria-labelledby="csFaqTitle">
  <div class="pt-inner cs-faq-grid">
    <div class="cs-sec-head">
      <span class="eyebrow eyebrow--rule">04 · Questions</span>
      <h2 id="csFaqTitle">Frequently asked.</h2>
      <p>General information only. Your prescriber and pharmacist are the right people for advice about you.</p>
    </div>
    <div class="cs-faq">
${faq}
    </div>
  </div>
</section>

<section class="pt-plate pt-sec pt-sec--ink cs-sec" id="about" aria-labelledby="csAboutTitle">
  <div class="pt-inner">
    <div class="cs-sec-head">
      <span class="eyebrow eyebrow--rule">05 · Background</span>
      <h2 id="csAboutTitle">About medicinal cannabis, and about us.</h2>
    </div>
    <div class="cs-cols">
      <div class="cs-col"><h3>Medicinal cannabis in New Zealand</h3><p>Under the Medicinal Cannabis Scheme, products must meet a minimum quality standard before they can be supplied. They are prescription medicines: a registered prescriber decides whether one is appropriate, and a pharmacy dispenses it. Products come in different forms, including dried flower and oils.</p></div>
      <div class="cs-col"><h3>Aho Farms products, at a high level</h3><p>Aho Farms is a Māori-owned licensed cultivator in Hawke's Bay. We grow and test dried medicinal cannabis flower, offered to prescribers under the RĀ and SOURCE ranges. Which product, if any, suits you is your prescriber's decision. <a href="/products.html">Read about how we grow</a>.</p></div>
      <div class="cs-col"><h3>Markets we currently support</h3><p>We connect consumers with approved prescriber partners in these markets. Availability of products varies by country and pharmacy; your prescriber or pharmacist can tell you what is currently available.</p>
        <ul class="cs-markets" aria-label="Supported markets">
        ${marketChips}
        </ul></div>
    </div>
    <p class="cs-fineprint cs-fineprint--dark">Aho Farms products are prescription medicines. This page is general information, not medical advice and not an advertisement for any product.</p>
  </div>
</section>

<section class="pt-plate pt-sec plate--flax cs-sec" id="support" aria-labelledby="csSupportTitle">
  <div class="pt-inner cs-support-grid cs-support-grid--single">
    <div>
      <span class="eyebrow eyebrow--rule">06 · Patient support</span>
      <h2 id="csSupportTitle">Support and referral information.</h2>
      <div class="cs-support-list cs-support-list--cols">
        <p><b>Already submitted an enquiry?</b>Your next step was shown on screen and, where a prescriber partner is set up for your market, emailed to you with a reference code. If you cannot find it, email us with your name and country and we will resend it.</p>
        <p><b>Questions about a medicine you have been prescribed?</b>Your pharmacist or prescriber is the right first call. For a side effect that worries you, contact your prescriber; in an emergency call 111 (New Zealand) or your local emergency number.</p>
        <p><b>General enquiries</b><a href="mailto:${esc(c.support.email)}">${esc(c.support.email)}</a> · <a href="/contact.html">Contact page</a></p>
      </div>
      <div class="btn-row"><a class="btn btn--primary" href="#get-connected">Get Connected to a Prescriber</a></div>
    </div>
  </div>
</section>
<p class="pt-legal">${LEGAL}</p>`;
  return shell({ depth: 2, title: 'Consumer Portal · Get Connected to a Prescriber | Aho Farms', description: 'Understand how medicinal cannabis access works and get connected to an approved, independent prescriber partner for your country.', portalId: c.id, page: 'consumer', main, scripts: ['assets/vendor/qrcode.min.js'] });
}

function hubPage(all, consumer, isPublic) {
  all = all.filter(p => isPublic(p.id));
  const consumerCard = !isPublic(consumer.id) ? '' : `    <a class="card" href="/portal/${consumer.id}/index.html">
      <span class="eyebrow">${esc(consumer.short)} · Public</span>
      <h2>${esc(consumer.name)}</h2>
      <p>${esc(consumer.tagline)}</p>
      <span class="pt-cta">Get connected</span>
    </a>\n`;
  const cards = consumerCard + all.map(p => `    <a class="card" href="/portal/${p.id}/login.html">
      <span class="eyebrow">${esc(p.short)}</span>
      <h2>${esc(p.name)}</h2>
      <p>${esc(p.tagline)}</p>
      <span class="pt-cta">Sign in</span>
    </a>`).join('\n');
  const main = `<section class="pt-plate pt-hub" aria-labelledby="ptTitle">
  <div class="pt-hub-head">
    <span class="eyebrow eyebrow--rule">Aho Farms · Portals</span>
    <h1 id="ptTitle">Pick up the thread.</h1>
    <p class="pt-lead">${all.length ? 'One gateway for every audience. Consumers can understand the access pathway and get connected to a prescriber partner without signing in. The professional portals are protected: every account is verified by Aho Farms before it is approved, and each portal only opens to the accounts approved for it.' : 'Start here if you are a patient or carer. Understand how medicinal cannabis access works and get connected to an approved, independent prescriber partner for your country.'}</p>
  </div>
  <div class="pt-hub-grid">
${cards}
  </div>
  <p class="pt-hub-signed" id="ptHubSigned" hidden>You are signed in. <a class="pt-link" href="#">Open My Portal</a></p>
</section>
<p class="pt-legal">${LEGAL}</p>`;
  const desc = all.length
    ? `Aho Farms portals: ${[isPublic(consumer.id) ? 'the Consumer Portal' : null, ...all.map(p => p.name)].filter(Boolean).join(', ')}.`
    : 'Understand how medicinal cannabis access works and get connected to an approved, independent prescriber partner for your country.';
  return shell({ depth: 1, title: 'Portals | Aho Farms', description: desc, portalId: '', page: 'hub', main });
}

(async () => {
  const { PORTALS, CONSUMER } = await import('../lib/portals.js');
  const markets = await import('../lib/markets.js');
  const write = (rel, html) => { fs.mkdirSync(path.dirname(path.join(ROOT, rel)), { recursive: true }); fs.writeFileSync(path.join(ROOT, rel), html); };
  const { isPublic } = await import('../lib/flags.js');
  write('portal/index.html', hubPage(PORTALS, CONSUMER, isPublic));
  write(`portal/${CONSUMER.id}/index.html`, consumerPage(CONSUMER, PORTALS, markets));
  for (const p of PORTALS) {
    write(`portal/${p.id}/login.html`, loginPage(p, PORTALS));
    write(`portal/${p.id}/request-access.html`, requestPage(p, PORTALS));
    write(`portal/${p.id}/forgot.html`, forgotPage(p));
    write(`portal/${p.id}/reset.html`, resetPage(p));
    write(`portal/${p.id}/home.html`, homePage(p));
    write(`portal/${p.id}/account.html`, accountPage(p));
  }
  console.log(`portal pages built: hub + consumer portal + ${PORTALS.length} portals × 6 pages`);
})().catch(e => { console.error(e); process.exit(1); });
