// Single source of truth for site navigation.
// te reo labels are PROVISIONAL - pending review by a fluent speaker.

const SENTINEL_START = '<!-- AHO:NAV:START - generated by scripts/propagate-nav.js, do not edit by hand -->';
const SENTINEL_END = '<!-- AHO:NAV:END -->';

const NAV = [
  {
    en: 'Learn', mi: 'Ako', href: 'about.html',
    children: [
      { en: 'About',        mi: 'Mō Mātou',          href: 'about.html' },
      { en: 'Our Origins',  mi: 'Ō Mātou Takenga',   href: 'origins.html' },
      // Our Board is deliberately NOT a nav item — the board is being folded
      // into the Our Team page. board.html still exists and still resolves.
      { en: 'Our Team',     mi: 'Tō Mātou Tīma',     href: 'team.html' },
      { en: 'Logo story',   mi: 'Tō Mātou Tohu',     href: 'tohu.html' },
      // Our Whenua + Cultivation were merged into one item (CEO, 2026-09-08);
      // both lived on cultivation.html. te reo reuses the two existing labels.
      { en: 'Land & Cultivation', mi: 'Whenua · Māra Hua', href: 'cultivation.html' },
      { en: 'Quality',      mi: 'Te Whakamātau',     href: 'quality.html' },
      { en: 'News',         mi: 'Ngā Kōrero',        href: 'news.html' },
    ],
  },
  {
    en: 'Buy', mi: 'Hoko', href: 'products.html',
    children: [
      { en: 'Products',     mi: 'Ngā Hua',           href: 'products.html' },
      { en: 'Partnerships', mi: 'Ngā Hoa',           href: 'index.html#portals' },
    ],
  },
  {
    en: 'Invest', mi: 'Haumi', href: 'investors.html',
    children: [],
  },
];

const CTA = { en: 'Contact', mi: 'Whakapā Mai', href: 'contact.html' };

module.exports = { NAV, CTA, SENTINEL_START, SENTINEL_END };
