// Propagates the two-tier nav markup to every page and keeps the legacy
// pages' token aliases in step with the shared design system.
//
// Since the 2026-09-14 design audit the nav CSS and JS live in
// assets/aho-chrome.css / assets/aho-chrome.js (stamped by
// scripts/propagate-chrome.js), so this script no longer ports anything
// from a donor page. What it still does, idempotently:
//   1. stamps the generated <nav> between the AHO:NAV sentinels
//   2. on legacy (non-v6) pages, keeps a small :root alias block between the
//      AHO:NAVCSS sentinels so the names their inline CSS uses
//      (--gold, --s1..--s7, --font-h ...) resolve to the shared --aho-* tokens
//   3. removes any leftover AHO:NAVJS block (the nav script is shared now)
//   4. pins the fixed-header portals below the site nav via --nav-h
//   5. normalises the Google Fonts request and a few stale links
//
// Preserves each file's own line-ending convention (index.html is CRLF;
// every other page in this repo is LF) - never mass-converts.
//
// Run order after any nav/footer/social change:
//   node scripts/propagate-nav.js && node scripts/propagate-chrome.js && node scripts/check-nav.js

const fs = require('fs');
const path = require('path');
const { renderNav, relativize, prefixFor } = require('./render-nav');
const { SENTINEL_START, SENTINEL_END } = require('./nav-config');

const ROOT = path.join(__dirname, '..');
const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
function expect(cond, msg) { if (!cond) throw new Error('propagate-nav: ' + msg); }

// v6 pages carry the design system natively; everything else is "legacy"
// and gets the alias block.
const V6_PAGES = new Set(['index.html', 'about.html', 'origins.html', 'team.html', 'tohu.html', 'cultivation.html',
  'quality.html', 'products.html', 'board.html', 'business.html', 'whats-new.html']);
// Portals with their own fixed app header, pushed below the site nav.
// (The 2026-09 portal shells were retired on 2026-09-20 for the protected
// /portal/<id>/ pages generated by scripts/build-portals.js; empty set kept
// so the offset logic stays available for any future app-shell page.)
const FIXED_HEADER_PORTALS = new Set();
// The generated portal pages (portal/index.html, portal/<id>/*.html) use the
// design-system tokens natively and sit one or two directories deep, so
// their stamped links are prefixed with ../ per level.
const isPortalPage = f => f.startsWith('portal/');
// Pages with no site-header <nav> of their own: the sentinel block goes
// right after <body>. (The three portals have a sidebar <nav> that must
// never be searched-and-replaced.)
const INSERT_AFTER_BODY = new Set(['404.html', ...FIXED_HEADER_PORTALS]);

const OWN_SENTINELS = {
  css: ['/* AHO:NAVCSS:START - generated by scripts/propagate-nav.js, do not edit by hand */',
        '/* AHO:NAVCSS:END */'],
  js: ['<!-- AHO:NAVJS:START - generated by scripts/propagate-nav.js, do not edit by hand -->',
       '<!-- AHO:NAVJS:END -->'],
};

// Legacy token names -> shared tokens. Only stamped where the page does not
// already define the name itself (its own :root wins for anything else).
const ALIASES = {
  // "gold" in legacy page CSS means "the page accent": gold on Palette 1,
  // teal on Palette 2 (data-palette="teal"). Never both on one page.
  'gold': 'var(--aho-accent)', 'gold-light': 'var(--aho-accent-light)', 'gold-border': 'var(--aho-accent-soft)',
  'hairline': 'var(--aho-hair)', 'max': 'var(--aho-max)',
  's1': 'var(--s1)', 's2': 'var(--s2)', 's3': 'var(--s3)', 's4': 'var(--s4)', 's5': 'var(--s5)', 's6': 'var(--s6)', 's7': 'var(--s7)',
  'silver': 'var(--aho-silver)', 'starlight': 'var(--aho-white)', 'void': 'var(--aho-void)',
  'ease': 'var(--aho-ease)', 'font-h': 'var(--aho-font-h)', 'font-b': 'var(--aho-font-b)',
};

const FONTS_HREF = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;1,400;1,500&family=Inter:wght@400;500;600&display=swap';

function detectEOL(raw) {
  const crlf = (raw.match(/\r\n/g) || []).length;
  const bareLf = (raw.match(/[^\r]\n/g) || []).length;
  return crlf > bareLf ? '\r\n' : '\n';
}
function toEOL(text, eol) {
  const normalized = text.replace(/\r\n/g, '\n');
  return eol === '\n' ? normalized : normalized.replace(/\n/g, eol);
}

function sentinelSwapOrInsert(html, [a, b], block, insertBeforeRe, label) {
  const re = new RegExp(esc(a) + '[\\s\\S]*?' + esc(b));
  if (re.test(html)) return html.replace(re, a + '\n' + block + '\n' + b);
  const m = html.match(insertBeforeRe);
  expect(m, `nowhere to insert ${label}`);
  return html.slice(0, m.index) + a + '\n' + block + '\n' + b + '\n' + html.slice(m.index);
}

function processPage(file) {
  const full = path.join(ROOT, file);
  const raw = fs.readFileSync(full, 'utf8');
  const eol = detectEOL(raw);
  let html = toEOL(raw, '\n');

  // ---- 1. nav markup ----
  const navBlock = renderNav(file); // already relativized for nested pages
  const navRe = new RegExp(esc(SENTINEL_START) + '[\\s\\S]*?' + esc(SENTINEL_END));
  if (navRe.test(html)) {
    html = html.replace(navRe, SENTINEL_START + '\n' + navBlock + '\n' + SENTINEL_END);
  } else if (INSERT_AFTER_BODY.has(file)) {
    const m = html.match(/<body[^>]*>/);
    expect(m, `${file}: no <body> to insert nav after`);
    const idx = m.index + m[0].length;
    html = html.slice(0, idx) + '\n\n' + SENTINEL_START + '\n' + navBlock + '\n' + SENTINEL_END + html.slice(idx);
  } else {
    const allNavs = html.match(/<nav[^>]*>/gi) || [];
    const old = html.match(/<nav[\s\S]*?<\/nav>/);
    expect(old && allNavs.length === 1, `${file}: cannot identify a single site <nav> to replace - add it to INSERT_AFTER_BODY`);
    html = html.replace(old[0], SENTINEL_START + '\n' + navBlock + '\n' + SENTINEL_END);
  }

  // ---- 2. legacy alias block ----
  if (!V6_PAGES.has(file) && !isPortalPage(file)) {
    const withoutBlock = html.replace(new RegExp(esc(OWN_SENTINELS.css[0]) + '[\\s\\S]*?' + esc(OWN_SENTINELS.css[1])), '');
    const rootBlocks = withoutBlock.match(/:root\s*\{[\s\S]*?\}/g) || [];
    const defined = rootBlocks.join('\n');
    const decls = Object.entries(ALIASES)
      .filter(([name]) => !new RegExp('--' + esc(name) + '\\s*:').test(defined))
      .map(([name, value]) => `  --${name}: ${value};`);
    if (FIXED_HEADER_PORTALS.has(file)) decls.push('  --nav-h: 72px;');
    const block = decls.length ? `:root{\n${decls.join('\n')}\n}` : '/* all shared tokens defined by the page */';
    html = sentinelSwapOrInsert(html, OWN_SENTINELS.css, block, /<\/style>/, 'alias block');
  }

  // ---- 3. drop any leftover ported nav script ----
  html = html.replace(new RegExp('\\n?' + esc(OWN_SENTINELS.js[0]) + '[\\s\\S]*?' + esc(OWN_SENTINELS.js[1]) + '\\n?'), '\n');

  // ---- 4. portal offsets (fixed point once applied) ----
  if (FIXED_HEADER_PORTALS.has(file)) {
    html = html
      .replace(/top:\s*0;\s*left:\s*0;\s*right:\s*0;/, 'top: var(--nav-h); left: 0; right: 0;')
      .replace(/top:\s*var\(--header-h\)/g, 'top: calc(var(--header-h) + var(--nav-h))')
      .replace(/padding-top:\s*var\(--header-h\)/g, 'padding-top: calc(var(--header-h) + var(--nav-h))')
      .replace(/margin-top:\s*var\(--header-h\)/g, 'margin-top: calc(var(--header-h) + var(--nav-h))')
      .replace(/calc\(100vh - var\(--header-h\)\)/g, 'calc(100vh - var(--header-h) - var(--nav-h))')
      .replace(/calc\(var\(--header-h\) \+ 45px\)/g, 'calc(var(--header-h) + var(--nav-h) + 45px)');
  }

  // ---- 5. fonts + stale refs ----
  html = html.replace(/https:\/\/fonts\.googleapis\.com\/css2\?family=Cormorant[^"']+/, FONTS_HREF);
  html = html.replace(/export\.html/g, 'export-partners.html');
  html = html.replace(/©\s*2025/g, '© 2026');

  fs.writeFileSync(full, toEOL(html, eol));
  return V6_PAGES.has(file) || isPortalPage(file) ? 'v6' : 'legacy';
}

const { listPages } = require('./propagate-nav-pages');
const pages = listPages();
const counts = { v6: 0, legacy: 0 };
pages.forEach(p => { counts[processPage(p)]++; });
console.log(`nav stamped on ${pages.length} pages (${counts.v6} v6, ${counts.legacy} legacy with alias block)`);
