// Stamps the shared chrome onto every page (CEO site-wide feedback,
// 2026-09-10): the aho-chrome.css link, the aho-chrome.js script, the
// simplified footer and the floating "Connect with us" button + sheet.
//
// Idempotent, sentinel-delimited, and preserves each file's own line
// endings (index.html is CRLF, everything else LF) - same discipline as
// propagate-nav.js. Run AFTER propagate-nav.js when the nav changes:
//   node scripts/propagate-nav.js && node scripts/propagate-chrome.js && node scripts/check-nav.js
//
// Portals (logged-in app shells) get the stylesheet and script but keep
// their own footer and do not get the floating button.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { SOCIAL, CONNECT } = require('./nav-config');

const ROOT = path.join(__dirname, '..');

// vercel.json serves /assets with a one-year immutable cache, so the chrome
// css/js links carry a content hash: any edit to either file changes the URL
// and every returning browser refetches it. Re-run this script after editing
// assets/aho-chrome.css or assets/aho-chrome.js.
const assetVersion = (rel) =>
  crypto.createHash('sha1').update(fs.readFileSync(path.join(ROOT, rel))).digest('hex').slice(0, 8);
const CSS_HREF = `assets/aho-chrome.css?v=${assetVersion('assets/aho-chrome.css')}`;
const JS_SRC = `assets/aho-chrome.js?v=${assetVersion('assets/aho-chrome.js')}`;
const PORTALS = new Set(['export-portal.html', 'investors-portal.html', 'pharmacies-portal.html', 'prescribers-portal.html']);
const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const escHtml = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const S = {
  css: ['<!-- AHO:CHROME:CSS:START - generated by scripts/propagate-chrome.js, do not edit by hand -->', '<!-- AHO:CHROME:CSS:END -->'],
  js: ['<!-- AHO:CHROME:JS:START - generated by scripts/propagate-chrome.js, do not edit by hand -->', '<!-- AHO:CHROME:JS:END -->'],
  footer: ['<!-- AHO:FOOTER:START - generated by scripts/propagate-nav.js, do not edit by hand -->', '<!-- AHO:FOOTER:END -->'],
  connect: ['<!-- AHO:CONNECT:START - generated by scripts/propagate-chrome.js, do not edit by hand -->', '<!-- AHO:CONNECT:END -->'],
};

function detectEOL(raw) {
  const crlf = (raw.match(/\r\n/g) || []).length;
  const bareLf = (raw.match(/[^\r]\n/g) || []).length;
  return crlf > bareLf ? '\r\n' : '\n';
}
const toEOL = (t, eol) => (eol === '\n' ? t.replace(/\r\n/g, '\n') : t.replace(/\r\n/g, '\n').replace(/\n/g, eol));

function socialList(cls) {
  return `<ul class="${cls}" aria-label="Aho Farms on social media">\n` +
    SOCIAL.map(s => `  <li><a href="${escHtml(s.href)}" target="_blank" rel="noopener" aria-label="${escHtml(s.name)}">${s.icon}</a></li>`).join('\n') +
    '\n</ul>';
}

const FOOTER_HTML = `<footer class="aho-footer" id="contact">
  <div class="aho-wrap">
    <div class="aho-footer-top">
      <div>
        <a href="index.html" class="aho-footer-logo" aria-label="Aho Farms home"><span class="aho-mark" aria-hidden="true"></span></a>
        <div class="aho-footer-badge">Māori Owned &amp; Operated</div>
        <p class="aho-footer-intro">Cultivating wellness from ancestral lands. Premium medicinal cannabis grown with respect for the whenua and the people.</p>
        ${socialList('aho-footer-social').replace(/\n/g, '\n        ')}
      </div>
      <div class="aho-footer-col">
        <h5>Portals</h5>
        <ul>
${CONNECT.filter(c => c.portal).map(c => `          <li><a href="${escHtml(c.href)}">${escHtml(c.label)}</a></li>`).join('\n')}
        </ul>
      </div>
      <div class="aho-footer-col">
        <h5>Contact</h5>
        <ul>
          <li><a href="contact.html">Contact the team</a></li>
          <li><a href="mailto:hello@ahofarms.co.nz">hello@ahofarms.co.nz</a></li>
          <li><a href="contact.html">Hawke's Bay<small>Aotearoa New Zealand</small></a></li>
        </ul>
      </div>
    </div>
    <div class="aho-footer-bottom">
      <div class="aho-footer-copy">
        © 2026 Aho Farms Limited ·
        <a href="privacy.html">Privacy</a> ·
        <a href="terms.html">Terms</a> ·
        <a href="disclaimer.html">Disclaimer</a>
      </div>
      <div class="aho-footer-legal">Aho Farms products are prescription medicines. Not for general sale. Licensed medicinal cannabis cultivator under New Zealand law.</div>
    </div>
  </div>
</footer>`;

const CONNECT_HTML = `<div class="aho-connect">
  <button class="aho-connect-btn" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="ahoConnectSheet">
    <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5h16v10H9l-4 3.5v-3.5H4z"/><path d="M8 9.5h8M8 12.5h5"/></svg>
    Connect with us
  </button>
</div>
<div class="aho-sheet" id="ahoConnectSheet" role="dialog" aria-modal="true" aria-labelledby="ahoConnectTitle" aria-hidden="true">
  <div class="aho-sheet-panel">
    <div class="aho-sheet-head">
      <div>
        <span class="aho-sheet-eyebrow">Whakapā mai</span>
        <h2 class="aho-sheet-title" id="ahoConnectTitle">Connect with us</h2>
      </div>
      <button class="aho-sheet-close" type="button" aria-label="Close"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg></button>
    </div>
    <ul class="aho-sheet-list">
${CONNECT.map(c => `      <li><a href="${escHtml(c.href)}"><span><b>${escHtml(c.label)}</b><small>${escHtml(c.note)}</small></span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></li>`).join('\n')}
    </ul>
  </div>
</div>`;

// beforeRes: candidate insertion points, first match wins. Some pages omit
// </head> entirely (valid HTML - about.html does), so the head insert falls
// back to "just before <body>", which is still inside the implied head.
function swapOrInsert(html, [a, b], block, beforeRes, label) {
  const re = new RegExp(esc(a) + '[\\s\\S]*?' + esc(b));
  if (re.test(html)) return html.replace(re, a + '\n' + block + '\n' + b);
  for (const beforeRe of [].concat(beforeRes)) {
    const m = html.match(beforeRe);
    if (m) return html.slice(0, m.index) + a + '\n' + block + '\n' + b + '\n' + html.slice(m.index);
  }
  throw new Error(`${label}: nowhere to insert`);
}

function processPage(file) {
  const full = path.join(ROOT, file);
  const raw = fs.readFileSync(full, 'utf8');
  const eol = detectEOL(raw);
  let html = toEOL(raw, '\n');
  const isPortal = PORTALS.has(file);

  html = swapOrInsert(html, S.css, `<link rel="stylesheet" href="${CSS_HREF}">`, [/<\/head>/, /<body[^>]*>/], `${file} chrome css`);
  html = swapOrInsert(html, S.js, `<script src="${JS_SRC}" defer></script>`, /<\/body>/, `${file} chrome js`);

  if (!isPortal) {
    const footRe = new RegExp(esc(S.footer[0]) + '[\\s\\S]*?' + esc(S.footer[1]));
    if (footRe.test(html)) {
      html = html.replace(footRe, S.footer[0] + '\n' + FOOTER_HTML + '\n' + S.footer[1]);
    } else {
      const old = html.match(/<footer[\s\S]*?<\/footer>/);
      if (!old) throw new Error(`${file}: no <footer> to replace`);
      html = html.replace(old[0], S.footer[0] + '\n' + FOOTER_HTML + '\n' + S.footer[1]);
    }
    // the connect block sits just before the chrome script
    const conRe = new RegExp(esc(S.connect[0]) + '[\\s\\S]*?' + esc(S.connect[1]));
    if (conRe.test(html)) html = html.replace(conRe, S.connect[0] + '\n' + CONNECT_HTML + '\n' + S.connect[1]);
    else html = html.replace(S.js[0], S.connect[0] + '\n' + CONNECT_HTML + '\n' + S.connect[1] + '\n' + S.js[0]);
  }

  fs.writeFileSync(full, toEOL(html, eol));
  return isPortal ? 'portal' : 'page';
}

const pages = fs.readdirSync(ROOT).filter(f => f.endsWith('.html'));
const counts = { page: 0, portal: 0 };
pages.forEach(p => { counts[processPage(p)]++; });
console.log(`chrome stamped on ${pages.length} pages (${counts.page} with footer + connect, ${counts.portal} portals css/js only)`);
